/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue audit ZIP export job */
        post: operations["enqueueAuditZip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get audit ZIP job status */
        get: operations["getAuditZipJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditZipRequest: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            partner?: string | null;
            /** @enum {string} */
            format: "zip";
        };
        AuditZipJob: {
            /** Format: uuid */
            jobId: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "canceled";
            /** Format: date-time */
            requestedAt?: string;
            /** Format: date-time */
            completedAt?: string | null;
            result?: components["schemas"]["AuditZipResult"];
            error?: components["schemas"]["InternalError"];
        };
        AuditZipResult: {
            /**
             * Format: uri
             * @description Signed URL valid for configured TTL (default 10 minutes)
             */
            signedUrl: string;
            /** @description Size in bytes */
            size: number;
        };
        ValidationError: {
            errors: {
                /** @example AUDIT-REQ-001 */
                code: string;
                path: string;
                message: string;
            }[];
        };
        ForbiddenError: {
            /** @example FORBIDDEN */
            code: string;
            /** @example Tenant or role missing */
            message: string;
        };
        ConflictError: {
            /** @example CONFLICT */
            code: string;
            /** @example Duplicate request */
            message: string;
        };
        NotFoundError: {
            /** @example NOT_FOUND */
            code: string;
            message: string;
        };
        InternalError: {
            /** @example INTERNAL_ERROR */
            code: string;
            message: string;
            retryable: boolean;
        };
    };
    responses: {
        /** @description Generic success placeholder (for lint rule; concrete 2xx responses are defined per operation) */
        "2xxSuccess": {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Request validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationError"];
            };
        };
        /** @description Job accepted */
        AuditJobAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuditZipJob"];
            };
        };
        /** @description Job status */
        AuditJobStatus: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuditZipJob"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ForbiddenError"];
            };
        };
        /** @description Conflict (duplicate job) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ConflictError"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["InternalError"];
            };
        };
    };
    parameters: {
        /** @description Correlation ID for tracing and audit hash chain */
        CorrelationId: string;
        /** @description Tenant identifier for RBAC and storage segregation */
        TenantId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    enqueueAuditZip: {
        parameters: {
            query?: never;
            header: {
                /** @description Correlation ID for tracing and audit hash chain */
                "X-Correlation-Id": components["parameters"]["CorrelationId"];
                /** @description Tenant identifier for RBAC and storage segregation */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditZipRequest"];
            };
        };
        responses: {
            202: components["responses"]["AuditJobAccepted"];
            400: components["responses"]["ValidationError"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getAuditZipJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Correlation ID for tracing and audit hash chain */
                "X-Correlation-Id": components["parameters"]["CorrelationId"];
                /** @description Tenant identifier for RBAC and storage segregation */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AuditJobStatus"];
            403: components["responses"]["Forbidden"];
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
